name: GitHub Actions Demo
on: 
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "dev" ]

jobs:
  app:
    runs-on: ubuntu-latest
    name: Run app image
    steps:
      - run: docker build --tag devops-project --target devops-project .
      - run: docker run --name=devops-project -d --network host devops-project
      
  tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - run: docker build --tag devops-project-test --target devops-project-test .
      - run: docker run --name=devops-project-test -d --network host devops-project-test