name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  build-app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the app image
      run: docker build --file Dockerfile --tag devops-project:latest --target devops-project .
    - name: Run the app image
      run: docker run --name=devops-project -d --network host devops-project:latest
 
  build-tests:
    needs: run-app
    runs-on: ubuntu-latest
    steps:
    - name: Build the tests image
      run: docker build --file Dockerfile --tag devops-project-test:latest --target devops-project-test .
    - name: Run the tests image
      run: docker run --name=devops-project-test -d --network host devops-project-test:latest